# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{extjs-mvc}
  s.version = "0.4.0.f"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ed Spencer and Chris Scott"]
  s.date = %q{2010-03-15}
  s.default_executable = %q{extjs-mvc}
  s.description = %q{A full-stack, Rails-like MVC for the Ext JS javascript framework (originally known as extmvc/extmvc)}
  s.email = %q{christocracy@gmail.com}
  s.executables = ["extjs-mvc"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/extjs-mvc",
     "lib/extjs-mvc.rb",
     "lib/extjs-mvc/api.rb",
     "lib/src/App.js",
     "lib/src/MVC.js",
     "lib/src/Presenter.js",
     "lib/src/README.rdoc",
     "lib/src/controller/Controller.js",
     "lib/src/controller/CrudController.js",
     "lib/src/lib/Array.js",
     "lib/src/lib/Booter.js",
     "lib/src/lib/ClassManager.js",
     "lib/src/lib/ControllerClassManager.js",
     "lib/src/lib/Dependencies.js",
     "lib/src/lib/DispatchMatcher.js",
     "lib/src/lib/Dispatcher.js",
     "lib/src/lib/Environment.js",
     "lib/src/lib/Inflector.js",
     "lib/src/lib/ModelClassManager.js",
     "lib/src/lib/Route.js",
     "lib/src/lib/Router.js",
     "lib/src/lib/String.js",
     "lib/src/lib/ViewClassManager.js",
     "lib/src/lib/notes.txt",
     "lib/src/model/AdapterManager.js",
     "lib/src/model/Association.js",
     "lib/src/model/Base.js",
     "lib/src/model/BelongsToAssociation.js",
     "lib/src/model/Cache.js",
     "lib/src/model/HasManyAssociation.js",
     "lib/src/model/Model.js",
     "lib/src/model/UrlBuilder.js",
     "lib/src/model/adapters/AbstractAdapter.js",
     "lib/src/model/adapters/MemoryAdapter.js",
     "lib/src/model/adapters/RESTAdapter.js",
     "lib/src/model/adapters/RESTJSONAdapter.js",
     "lib/src/model/adapters/notes.txt",
     "lib/src/model/associations/Association.js",
     "lib/src/model/associations/notes.txt",
     "lib/src/model/validations/Errors.js",
     "lib/src/model/validations/Plugin.js",
     "lib/src/model/validations/Validations.js",
     "lib/src/notes/Charts.graffle",
     "lib/src/overrides/Ext.Component.js",
     "lib/src/overrides/Ext.extend.js",
     "lib/src/spec/Array.spec.js",
     "lib/src/spec/ExtMVC.spec.js",
     "lib/src/spec/Model.spec.js",
     "lib/src/spec/OS.spec.js",
     "lib/src/spec/Router.spec.js",
     "lib/src/spec/SpecHelper.js",
     "lib/src/spec/String.spec.js",
     "lib/src/spec/model/AbstractAdapter.spec.js",
     "lib/src/spec/model/Associations.spec.js",
     "lib/src/spec/model/Cache.spec.js",
     "lib/src/spec/model/RESTAdapter.spec.js",
     "lib/src/spec/model/ValidationErrors.spec.js",
     "lib/src/spec/model/Validations.spec.js",
     "lib/src/spec/model/ValidationsPlugin.spec.js",
     "lib/src/spec/suite.html",
     "lib/src/specs-old/JSSpec.css",
     "lib/src/specs-old/JSSpec.js",
     "lib/src/specs-old/all.html",
     "lib/src/specs-old/base.js",
     "lib/src/specs-old/controller.js",
     "lib/src/specs-old/diff_match_patch.js",
     "lib/src/specs-old/model.js",
     "lib/src/specs-old/route.js",
     "lib/src/specs-old/router.js",
     "lib/src/specs-old/string.js",
     "lib/src/testrunner/JSpecFormatter.js",
     "lib/src/testrunner/TestClient.js",
     "lib/src/testrunner/TestGrid.js",
     "lib/src/testrunner/TestRunner.js",
     "lib/src/testrunner/TestViewport.js",
     "lib/src/vendor.yml",
     "lib/src/vendor/ext-3.1.1/vendor.yml",
     "lib/src/view/FormWindow.js",
     "lib/src/view/HasManyEditorGridPanel.js",
     "lib/src/view/scaffold/Edit.js",
     "lib/src/view/scaffold/Index.js",
     "lib/src/view/scaffold/New.js",
     "lib/src/view/scaffold/ScaffoldFormPanel.js",
     "lib/vendor.yml",
     "test/helper.rb",
     "test/test_extjs-mvc-gem.rb"
  ]
  s.homepage = %q{http://github.com/christocracy/extjs-mvc}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A Rails-like, full-stack MVC framework for the Ext JS javascript framework}
  s.test_files = [
    "test/helper.rb",
     "test/test_extjs-mvc-gem.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<xmvc>, [">= 0.1.6"])
      s.add_runtime_dependency(%q<extjs>, [">= 0.1.1"])
      s.add_runtime_dependency(%q<git>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0.13.4"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<xmvc>, [">= 0.1.6"])
      s.add_dependency(%q<extjs>, [">= 0.1.1"])
      s.add_dependency(%q<git>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0.13.4"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<xmvc>, [">= 0.1.6"])
    s.add_dependency(%q<extjs>, [">= 0.1.1"])
    s.add_dependency(%q<git>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0.13.4"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

